@php $title = 'Kontakt – Blende 6 Fotografie'; @endphp
@extends('marketing.layout')
@section('marketing-content')
<main>
    <section class="bg-[#e8ede7] px-5 py-20 text-center md:px-10 md:py-28"><p class="text-[10px] font-semibold uppercase tracking-[.24em] text-[#778579]">Schreib mir</p><h1 class="mt-4 font-serif text-6xl tracking-tight md:text-8xl">Kontakt</h1><p class="mx-auto mt-5 max-w-2xl text-sm leading-7 text-[#687169]">Schön, dass du den Weg hierher gefunden hast. Ich freue mich schon auf deine Nachricht. 😀</p></section>
    <section class="mx-auto grid max-w-6xl gap-8 px-5 py-20 md:grid-cols-[.9fr_1.1fr] md:px-10 md:py-28">
        <aside class="rounded-[2rem] bg-[#435243] p-8 text-white md:p-10"><img src="{{ asset('images/blende6-logo.png') }}" alt="Blende 6" class="w-64 rounded-2xl bg-white/95 px-5 py-4"><h2 class="mt-10 font-serif text-3xl">Lina-Theresa Dick</h2><p class="mt-5 text-sm leading-7 text-white/75">Blende6 – Fotografie<br>Freiherr-vom-Stein-Straße 28<br>63695 Glauburg</p><div class="mt-7 space-y-2 text-sm"><a href="tel:+491785135299" class="block">0049 (0) 178 5135299</a><a href="mailto:info@blende6.de" class="block underline underline-offset-4">info@blende6.de</a><a href="https://www.instagram.com/blende6_fotografie/" class="block" rel="noopener" target="_blank">Instagram: @blende6_fotografie</a></div><a href="mailto:info@blende6.de?subject=Shooting-Anfrage" class="mt-9 inline-flex rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-[#435243]">E-Mail schreiben</a></aside>
        <div class="rounded-[2rem] border border-[#dfe2dd] bg-white p-8 md:p-10"><h2 class="font-serif text-4xl">Was darf in deine Nachricht?</h2><div class="mt-8 grid gap-7 sm:grid-cols-2"><div><h3 class="text-xs font-semibold uppercase tracking-[.14em] text-[#566258]">Kontaktaufnahme</h3><ul class="marketing-checklist mt-4"><li>Vor- und Nachname</li><li>E-Mail-Adresse</li><li>Telefonnummer (optional)</li></ul></div><div><h3 class="text-xs font-semibold uppercase tracking-[.14em] text-[#566258]">Unverbindliche Anfrage</h3><ul class="marketing-checklist mt-4"><li>Art des Shootings</li><li>Spezielle Wünsche</li><li>Gewünschte Dauer</li><li>Anzahl der Fotos</li><li>Anzahl der Personen</li><li>Gewünschter Ort</li><li>Datum, falls es bereits feststeht</li></ul></div></div><div class="mt-9 rounded-2xl bg-[#eef1ec] p-6"><p class="text-sm leading-7 text-[#687169]">Je mehr ich über deine Vorstellungen weiß, desto persönlicher kann ich dir antworten. Schreib einfach so, wie es für dich passt – ganz unkompliziert.</p></div></div>
    </section>
</main>
@endsection
