@php $title = 'Impressum – Blende 6 Fotografie'; @endphp
@extends('marketing.layout')
@section('marketing-content')
<main><section class="bg-[#e8ede7] px-5 py-20 text-center md:py-24"><h1 class="font-serif text-6xl tracking-tight">Impressum</h1></section><article class="legal-prose mx-auto max-w-4xl px-5 py-16 md:px-10 md:py-24">
    <h2>Angaben gemäß § 5 DDG</h2><p>Lina Dick<br>Freiherr-vom-Stein-Straße 28<br>63695 Glauburg</p><p><a href="mailto:info@blende6.de">info@blende6.de</a><br>0049 (0) 178 5135299</p><p>Steuer-ID: 41785091365</p>
    <h2>Verbraucherstreitbeilegung</h2><p>Wir nehmen nicht an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teil und sind hierzu nicht verpflichtet.</p>
    <h2>Haftung für Inhalte</h2><p>Als Diensteanbieter sind wir gemäß § 7 Abs. 1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen.</p><p>Die Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden entsprechender Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.</p>
    <h2>Haftung für Links</h2><p>Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für fremde Inhalte keine Gewähr übernehmen. Für die Inhalte verlinkter Seiten ist stets der jeweilige Anbieter oder Betreiber verantwortlich.</p><p>Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.</p>
    <h2>Urheberrecht</h2><p>Die durch die Seitenbetreiber erstellten Inhalte und Werke unterliegen dem deutschen Urheberrecht. Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedürfen der Zustimmung des jeweiligen Autors beziehungsweise Erstellers.</p><p>Soweit Inhalte nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Solltest du trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis.</p>
</article></main>
@endsection
