@php $title = 'Datenschutz – Blende 6 Fotografie'; @endphp
@extends('marketing.layout')
@section('marketing-content')
<main><section class="bg-[#e8ede7] px-5 py-20 text-center md:py-24"><h1 class="font-serif text-6xl tracking-tight">Datenschutz</h1></section><article class="legal-prose mx-auto max-w-4xl px-5 py-16 md:px-10 md:py-24">
    <h2>1. Information über die Erhebung personenbezogener Daten</h2><p>Im Folgenden informieren wir über die Erhebung personenbezogener Daten bei Nutzung unserer Website. Personenbezogene Daten sind alle Daten, die auf dich persönlich beziehbar sind, zum Beispiel Name, Adresse, E-Mail-Adressen oder Nutzerverhalten.</p><p>Verantwortlicher gemäß Art. 4 Abs. 7 EU-Datenschutz-Grundverordnung (DSGVO) ist:</p><p><strong>Blende 6 Fotografie · Lina Dick</strong><br>Freiherr-vom-Stein-Straße 28<br>63695 Glauburg<br>E-Mail: <a href="mailto:info@blende6.de">info@blende6.de</a></p><p>Bei einer Kontaktaufnahme per E-Mail werden die mitgeteilten Daten gespeichert, um deine Fragen zu beantworten. Rechtsgrundlage ist Art. 6 Abs. 1 S. 1 lit. a DSGVO. Die Daten werden gelöscht, sobald ihre Speicherung nicht mehr erforderlich ist, soweit keine gesetzlichen Aufbewahrungspflichten bestehen.</p>
    <h2>2. Deine Rechte</h2><p>Du hast gegenüber uns folgende Rechte hinsichtlich der dich betreffenden personenbezogenen Daten:</p><ul><li>Recht auf Auskunft</li><li>Recht auf Berichtigung oder Löschung</li><li>Recht auf Einschränkung der Verarbeitung</li><li>Recht auf Widerspruch gegen die Verarbeitung</li><li>Recht auf Datenübertragbarkeit</li></ul><p>Du hast zudem das Recht, dich bei einer Datenschutz-Aufsichtsbehörde über die Verarbeitung deiner personenbezogenen Daten zu beschweren.</p>
    <h2>3. Daten beim Besuch dieser Website</h2><p>Bei der informatorischen Nutzung werden nur die Daten erhoben, die dein Browser an den Server übermittelt und die technisch erforderlich sind, um die Website anzuzeigen und Stabilität und Sicherheit zu gewährleisten. Dazu gehören IP-Adresse, Datum und Uhrzeit, Zeitzone, aufgerufene Seite, HTTP-Statuscode, Datenmenge, Herkunftsseite, Browser, Betriebssystem sowie Sprache und Version der Browsersoftware. Rechtsgrundlage ist Art. 6 Abs. 1 S. 1 lit. f DSGVO.</p><p>Die Anwendung verwendet technisch notwendige Session-Cookies. Sie speichern eine Sitzungs-ID, damit Zugänge zu Eventgalerien und Formularvorgänge einem Browser zugeordnet werden können. Es werden keine Trackingprogramme eingesetzt.</p>
    <h2>4. Eventgalerien und Medien-Uploads</h2><p>Beim Hochladen von Fotos oder Videos werden der angegebene Name, eine freiwillig angegebene E-Mail-Adresse, die Mediendatei sowie technische Dateiinformationen gespeichert. Diese Daten dienen der Zuordnung und Verwaltung des jeweiligen Gast-Uploads innerhalb der ausgewählten Hochzeit beziehungsweise des Events.</p><p>Hochgeladene Medien sind für Personen sichtbar, die Zugang zur betreffenden Eventgalerie besitzen. Originaldateien können dort heruntergeladen werden. Bitte lade nur Inhalte hoch, für deren Weitergabe du berechtigt bist. Die Daten können durch den geschützten Master-Admin gelöscht werden.</p>
    <h2>5. Widerspruch und Widerruf</h2><p>Eine erteilte Einwilligung kann jederzeit widerrufen werden. Soweit die Verarbeitung auf einer Interessenabwägung beruht, kannst du aus Gründen, die sich aus deiner besonderen Situation ergeben, Widerspruch einlegen. Eine E-Mail an <a href="mailto:info@blende6.de">info@blende6.de</a> genügt.</p>
    <h2>6. Weitergabe von Daten</h2><p>Eine Übermittlung persönlicher Daten an Dritte erfolgt nur bei ausdrücklicher Einwilligung, zur Geltendmachung oder Verteidigung von Rechtsansprüchen, aufgrund einer gesetzlichen Verpflichtung oder soweit dies für die Abwicklung eines Vertragsverhältnisses erforderlich ist.</p>
    <h2>7. Datensicherheit</h2><p>Wir bedienen uns geeigneter technischer und organisatorischer Sicherheitsmaßnahmen, um Daten gegen Manipulation, Verlust, Zerstörung oder unbefugten Zugriff zu schützen. Die Sicherheitsmaßnahmen werden entsprechend der technologischen Entwicklung fortlaufend verbessert.</p>
    <h2>8. Drittanbieter und externe Links</h2><p>Diese Seite verwendet keine aktiven Social-Media-Plug-ins. Bei externen Links kann für die Inhalte der verlinkten Seiten keine Haftung übernommen werden; verantwortlich ist der jeweilige Betreiber.</p>
    <h2>9. Aktualität</h2><p>Diese Datenschutzerklärung wurde für die Eventgalerie und die übernommenen Blende-6-Inhalte ergänzt. Durch die Weiterentwicklung der Website oder geänderte gesetzliche Vorgaben kann eine Anpassung erforderlich werden.</p>
</article></main>
@endsection
