@php $title = 'Shootings – Blende 6 Fotografie'; @endphp
@extends('marketing.layout')
@section('marketing-content')
<main>
    <section class="bg-[#e8ede7] px-5 py-20 text-center md:px-10 md:py-28"><p class="text-[10px] font-semibold uppercase tracking-[.24em] text-[#778579]">Ganz du selbst</p><h1 class="mt-4 font-serif text-6xl tracking-tight md:text-8xl">Shootings</h1><p class="mx-auto mt-5 max-w-2xl text-sm leading-7 text-[#687169]">Natürliche, gefühlvolle Bilder in entspannter Atmosphäre – ohne steife Posen und ohne Perfektionsdruck.</p></section>
    <section class="mx-auto grid max-w-7xl gap-6 px-5 py-20 md:grid-cols-2 md:px-10 md:py-28">
        <article class="group relative min-h-[620px] overflow-hidden rounded-[2.5rem] text-white"><img src="{{ asset('images/blende6/weddings/wedding-018.jpg') }}" alt="Hochzeitsshooting von Blende 6" class="absolute inset-0 size-full object-cover transition duration-700 group-hover:scale-105"><div class="absolute inset-0 bg-gradient-to-t from-[#263229]/90 via-[#263229]/15 to-transparent"></div><div class="absolute inset-x-0 bottom-0 p-8 md:p-10"><p class="text-[10px] font-semibold uppercase tracking-[.2em] text-white/65">Euer besonderer Tag</p><h2 class="mt-3 font-serif text-5xl">Hochzeiten</h2><p class="mt-5 max-w-lg text-sm leading-7 text-white/75">Ich begleite euch an eurem besonderen Tag und halte große Emotionen sowie kleine Augenblicke in natürlichen Bildern fest.</p><a href="{{ route('marketing.portfolio') }}#hochzeiten" class="mt-7 inline-flex rounded-full bg-white px-6 py-3 text-sm font-semibold text-[#405045]">Hochzeiten ansehen</a></div></article>
        <article class="group relative min-h-[620px] overflow-hidden rounded-[2.5rem] text-white"><img src="{{ asset('images/blende6/portfolio/portfolio-018.jpg') }}" alt="Portraitshooting von Blende 6" class="absolute inset-0 size-full object-cover transition duration-700 group-hover:scale-105"><div class="absolute inset-0 bg-gradient-to-t from-[#263229]/90 via-[#263229]/15 to-transparent"></div><div class="absolute inset-x-0 bottom-0 p-8 md:p-10"><p class="text-[10px] font-semibold uppercase tracking-[.2em] text-white/65">Stark und einzigartig</p><h2 class="mt-3 font-serif text-5xl">Portraits</h2><p class="mt-5 max-w-lg text-sm leading-7 text-white/75">Am liebsten fotografiere ich draußen in der Natur. Dort entstehen mit natürlichem Licht lebendige und ausdrucksstarke Bilder, die dich so zeigen, wie du wirklich bist.</p><a href="{{ route('marketing.portfolio') }}#portraits" class="mt-7 inline-flex rounded-full bg-white px-6 py-3 text-sm font-semibold text-[#405045]">Portraits ansehen</a></div></article>
    </section>
    <section class="bg-[#435243] px-5 py-20 text-center text-white md:px-10 md:py-24"><p class="text-[10px] font-semibold uppercase tracking-[.24em] text-white/55">Deine Geschichte</p><h2 class="mx-auto mt-4 max-w-3xl font-serif text-5xl tracking-tight md:text-6xl">Du musst nicht wissen, wie man vor einer Kamera steht.</h2><p class="mx-auto mt-6 max-w-2xl text-sm leading-7 text-white/70">Meine offene und empathische Art schafft eine Atmosphäre, in der du dich wohlfühlen und ganz du selbst sein kannst. Daraus entstehen Bilder, die sich wirklich nach dir anfühlen.</p><a href="{{ route('marketing.contact') }}" class="mt-8 inline-flex rounded-full bg-white px-7 py-3.5 text-sm font-semibold text-[#435243]">Shooting anfragen</a></section>
</main>
@endsection
